name: workflow-con-push

# Se ejecuta cuando hay un push a la rama solo-ejemplo
on:
  push:
    branches: [ solo-ejemplo ]

jobs:
  validar:
    # Ejecuta el job en una máquina virtual Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Descarga el código del repositorio
      - name: Bajar codigo
        uses: actions/checkout@v4

      # Configura el entorno Python con la versión 3.10
      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      # Instala la librería pytest para ejecutar los tests
      - name: Instalar pytest
        run: pip install pytest

      # Ejecuta los tests del archivo test.py
      - name: Ejecutar pytest
        run: pytest test.py

      # Autenticarse en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construye y sube la imagen Docker a Docker Hub
      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v6
        with:
          context: .      # Indica el directorio donde se encuentra el Dockerfile
          push: true      # Sube la imagen al registro
          tags: benjaminrielli/wallet-app:latest  # Etiqueta de la imagen
